export const certificatesContent = {
  categories: [
    {
      id: "technical",
      name: "المهارات التقنية",
      icon: "code",
      color: "blue",
    },
    {
      id: "soft",
      name: "المهارات الناعمة",
      icon: "communication",
      color: "green",
    },
    {
      id: "design",
      name: "التصميم",
      icon: "design",
      color: "purple",
    },
    {
      id: "business",
      name: "الأعمال والتسويق",
      icon: "business",
      color: "orange",
    },
    {
      id: "development",
      name: "التطوير",
      icon: "development",
      color: "teal",
    },
  ],

  certificates: [
    {
      id: 1,
      title: "برنامج رواد مصر الرقمية - تطوير الواجهات الأمامية بتقنية React",
      image: "SoftwareDevelopmentReactFrontendWebDeveloper.png",
      issuer: "وزارة الاتصالات وتكنولوجيا المعلومات",
      category: "technical",
      date: "مايو 2025",
      duration: "نوفمبر إلى مايو 2025",
      score: "ممتاز",
      description:
        "برنامج متقدم في تطوير الواجهات الأمامية باستخدام React، يشمل مشاريع تطبيقية متقدمة وتدريب عملي مكثف تحت إشراف خبراء من الوزارة.",
      skills: [
        "React",
        "JavaScript",
        "HTML5",
        "CSS3",
        "Git",
        "Responsive Design",
        "API Integration",
      ],
      details: {
        program: "Digital Egypt Pioneers Program",
        specialization: "Software Development - React Frontend Web Developer",
        organization: "وزارة الاتصالات وتكنولوجيا المعلومات",
        period: "نوفمبر 2024 إلى مايو 2025",
        issuedBy: "د. هشام فاروق - مستشار تطوير التكنولوجيا بوزارة الاتصالات",
        validation:
          "شهادة معتمدة رسميًا من وزارة الاتصالات وتكنولوجيا المعلومات",
      },
    },
    {
      id: 2,
      title: "دورة اللغة الإنجليزية للأعمال - الجولة الثانية",
      image: "completedBusinessEnglishTrack.jpg",
      issuer: "وزارة الاتصالات وتكنولوجيا المعلومات",
      category: "soft",
      date: "مايو 2025",
      duration: "7 أشهر",
      score: "ممتاز",
      description:
        "دورة مكثفة في اللغة الإنجليزية للأعمال تحت مبادرة رواد مصر الرقمية، تركز على مهارات التواصل المهني والعرض التقديمي.",
      skills: [
        "Business English",
        "Professional Communication",
        "Presentation Skills",
        "Email Writing",
        "Negotiation",
      ],
      details: {
        program: "Business English Track - Round 2",
        organization:
          "وزارة الاتصالات وتكنولوجيا المعلومات - SYE English Community",
        period: "نوفمبر 2024 إلى مايو 2025",
        level: "متقدم",
        focus: "اللغة الإنجليزية للأعمال والمهارات المهنية",
      },
    },
    {
      id: 3,
      title: "دورة تصميم واجهات المستخدم وتجربة المستخدم (UX/UI)",
      image: "uix.jpg",
      issuer: "معهد تكنولوجيا المعلومات",
      category: "design",
      date: "أغسطس 2025",
      duration: "60 ساعة",
      score: "ممتاز",
      description:
        "دورة شاملة في أساسيات تصميم واجهات المستخدم وتجربة المستخدم، تشمل البحث والتخطيط والبروتوتايب والاختبار.",
      skills: [
        "UX Research",
        "UI Design",
        "Wireframing",
        "Prototyping",
        "Figma",
        "Adobe XD",
        "User Testing",
      ],
      details: {
        topics: [
          "UX Fundamentals & Design Research",
          "Design Process, Emphasis, Define and Ideate",
          "Concept to Low-Fidelity Prototyping",
          "High-Fidelity Prototyping to Post-Launch Analysis",
        ],
        totalHours: 60,
        institute: "معهد تكنولوجيا المعلومات (ITI)",
        issuedBy: "د. هبة صالح - رئيس معهد تكنولوجيا المعلومات",
      },
    },
    {
      id: 4,
      title: "دورة تطوير الواجهات الأمامية باستخدام React",
      image: "reactjs.jpg",
      issuer: "معهد تكنولوجيا المعلومات",
      category: "development",
      date: "سبتمبر 2024",
      duration: "150 ساعة",
      score: "ممتاز",
      description:
        "دورة متقدمة في تطوير الواجهات الأمامية باستخدام React وتقنيات الويب الحديثة، مع مشاريع عملية متكاملة.",
      skills: [
        "React.js",
        "JavaScript ES6+",
        "HTML5",
        "CSS3",
        "Bootstrap",
        "REST APIs",
        "State Management",
      ],
      details: {
        topics: ["JavaScript", "ECMA Script", "HTML5", "Bootstrap", "ReactJS"],
        totalHours: 150,
        period: "15 يوليو إلى 15 سبتمبر 2024",
        institute: "معهد تكنولوجيا المعلومات",
      },
    },
    {
      id: 5,
      title: "دورة تطوير التطبيقات باستخدام .NET",
      image: "dotnet.jpg",
      issuer: "معهد تكنولوجيا المعلومات",
      category: "development",
      date: "فبراير 2023",
      duration: "60 ساعة",
      score: "ممتاز",
      description:
        "دورة في تطوير التطبيقات باستخدام .NET و SQL Server، تشمل أساسيات البرمجة وقواعد البيانات.",
      skills: [
        ".NET",
        "C#",
        "SQL Server",
        "ASP.NET",
        "Entity Framework",
        "Database Design",
      ],
      details: {
        topics: [
          "C# Programming",
          "SQL Server",
          "ASP.NET MVC",
          "Entity Framework",
        ],
        totalHours: 60,
        period: "29 يناير إلى 9 فبراير 2023",
      },
    },
    {
      id: 6,
      title: "دورة SEO للمبتدئين",
      image: "SEO.png",
      issuer: "أكاديمية سلة",
      category: "business",
      date: "ديسمبر 2025",
      duration: "1 ساعة",
      score: "ممتاز",
      description:
        "دورة أساسية في تحسين محركات البحث (SEO) للمبتدئين، تغطي أساسيات SEO وممارسات تحسين المواقع.",
      skills: [
        "SEO Basics",
        "Keyword Research",
        "On-Page SEO",
        "Technical SEO",
        "Content Optimization",
      ],
      details: {
        instructor: "ركان الجهني",
        hours: 1,
        issuedDate: "4 ديسمبر 2025",
        platform: "أكاديمية سلة",
      },
    },
    {
      id: 7,
      title: "برنامج CIB الصيفي - The Green Leap",
      image: "CIB.jpg",
      issuer: "البنك التجاري الدولي (CIB)",
      category: "business",
      date: "يوليو 2025",
      duration: "شهر",
      score: "ممتاز",
      description:
        "برنامج تدريبي صيفي يركز على الاستدامة والتمويل الأخضر، يشمل ورش عمل وجلسات مع خبراء في القطاع المصرفي.",
      skills: [
        "Sustainable Finance",
        "ESG Principles",
        "Banking Operations",
        "Green Investments",
        "Corporate Sustainability",
      ],
      details: {
        program: "CIB Summer Program - The Green Leap",
        partners: ["Frankfurt School", "PROPARCO", "EUROMONEY", "X University"],
        focus: "التمويل الأخضر والاستدامة في القطاع المصرفي",
      },
    },
    {
      id: 8,
      title: "برنامج ALX للتنمية المهنية المعززة بالذكاء الاصطناعي",
      image: "AiCareerEssentials.png",
      issuer: "ALX",
      category: "soft",
      date: "أغسطس 2024",
      duration: "8 أسابيع",
      score: "ممتاز",
      description:
        "برنامج تطوير المهارات المهنية في العصر الرقمي باستخدام الذكاء الاصطناعي، يركز على القيادة والإبداع.",
      skills: [
        "AI Tools",
        "Professional Development",
        "Leadership",
        "Digital Communication",
        "Innovation",
      ],
      details: {
        program: "Augmented Professional Development Skills in the Digital Age",
        duration: "8 أسابيع",
        issuedBy: "ALX Group",
        validation: "شهادة معتمدة من ALX مع رمز التحقق",
      },
    },
    {
      id: 9,
      title: "دبلوم تطوير الواجهات الأمامية للويب",
      image: "SEF.jpeg",
      issuer: "مستقبل هندسة البرمجيات (SEF)",
      category: "development",
      date: "يوليو 2024",
      duration: "4 أشهر",
      score: "95.5%",
      description:
        "دبلوم متخصص في تطوير الواجهات الأمامية للويب، مع تقييم عملي شامل ومشاريع حقيقية.",
      skills: [
        "Frontend Development",
        "Web Standards",
        "Performance Optimization",
        "Cross-Browser Compatibility",
        "Web Accessibility",
      ],
      details: {
        studentId: "274122331",
        duration: "4 أشهر",
        score: "95.5%",
        issuedDate: "29 يوليو 2024",
      },
    },
    {
      id: 10,
      title: "دورة Empower Your Future",
      image: "EmpowerYourFuture.png",
      issuer: "Raya Customer Experience",
      category: "soft",
      date: "غير محدد",
      duration: "25 ساعة",
      score: "ممتاز",
      description:
        "دورة تدريبية لتمكين المستقبل تحت إشراف مؤسسة مصر الخير، تركز على تطوير المهارات الشخصية والمهنية.",
      skills: [
        "Personal Development",
        "Career Planning",
        "Communication Skills",
        "Problem Solving",
        "Teamwork",
      ],
      details: {
        hours: 25,
        funder: "Raya Customer Experience",
        implementer: "Rowad Initiative",
        supervisor: "مؤسسة مصر الخير",
      },
    },
    {
      id: 11,
      title: "دبلوم التسويق وإدارة وسائل التواصل الاجتماعي",
      image: "SocialMediaMarketingAndManagement.jpg",
      issuer: "Udemy - MTF Institute",
      category: "business",
      date: "يناير 2024",
      duration: "2 ساعة",
      score: "ممتاز",
      description:
        "دبلوم احترافي في التسويق وإدارة وسائل التواصل الاجتماعي، يشمل استراتيجيات التسويق الرقمي وإدارة المحتوى.",
      skills: [
        "Social Media Marketing",
        "Content Strategy",
        "Digital Advertising",
        "Analytics",
        "Brand Management",
      ],
      details: {
        certificateId: "UC-d33210be-6bcf-4cdd-b1c4-a07c3560a32a",
        issuedDate: "18 يناير 2024",
        duration: "2 ساعة",
        platform: "Udemy",
      },
    },
    {
      id: 12,
      title: "دورة ووردبريس السريعة: بناء أي موقع في دقائق",
      image: "wordpress.jpg",
      issuer: "Udemy - Meta Brains",
      category: "development",
      date: "أكتوبر 2025",
      duration: "2.5 ساعة",
      score: "ممتاز",
      description:
        "دورة سريعة لتعلم بناء مواقع الويب باستخدام ووردبريس، تشمل إدارة المحتوى والتخصيص المتقدم.",
      skills: [
        "WordPress",
        "CMS",
        "Theme Development",
        "Plugin Management",
        "Website Deployment",
      ],
      details: {
        certificateId: "UC-1b5f9aa7-7b81-47c7-8df8-ba59e4e83ac6",
        issuedDate: "13 أكتوبر 2025",
        duration: "2.5 ساعة",
        platform: "Udemy",
      },
    },
  ],
  labels: {
    allCertificates: "جميع الشهادات",
    showingXofY: "عرض {count} من {total} شهادة",
    certificateNumber: "الشهادة #{number}",
    viewFullDetails: "عرض التفاصيل الكاملة",
    downloadCertificate: "تحميل الشهادة",
    verifyCertificate: "التحقق من الشهادة",
    close: "إغلاق",

    // Categories
    technical: "تقنية",
    soft: "مهارات ناعمة",
    design: "تصميم",
    business: "أعمال وتسويق",
    development: "تطوير",

    // Components labels
    acquiredSkills: "المهارات المكتسبة",
    programDetails: "تفاصيل البرنامج",
    certificateDescription: "وصف الشهادة",
    duration: "المدة",
    skills: "مهارة",

    // Certificate details keys
    program: "البرنامج",
    specialization: "التخصص",
    organization: "الجهة",
    period: "الفترة",
    issuedBy: "صادر من",
    validation: "التحقق",
    level: "المستوى",
    focus: "التركيز",
    topics: "المواضيع",
    totalHours: "إجمالي الساعات",
    institute: "المعهد",
    instructor: "المدرب",
    issuedDate: "تاريخ الإصدار",
    platform: "المنصة",
    partners: "الشركاء",
    studentId: "رقم الطالب",
    score: "النتيجة",
    funder: "المانح",
    implementer: "المنفذ",
    supervisor: "المشرف",
    certificateId: "رقم الشهادة",
  },
};
