export const certificatesContent = {
  categories: [
    {
      id: "technical",
      name: "Technical Skills",
      icon: "code",
      color: "blue",
    },
    {
      id: "soft",
      name: "Soft Skills",
      icon: "communication",
      color: "green",
    },
    {
      id: "design",
      name: "Design",
      icon: "design",
      color: "purple",
    },
    {
      id: "business",
      name: "Business & Marketing",
      icon: "business",
      color: "orange",
    },
    {
      id: "development",
      name: "Development",
      icon: "development",
      color: "teal",
    },
  ],

  certificates: [
    {
      id: 1,
      title: "Digital Egypt Pioneers Program - React Frontend Web Developer",
      image: "SoftwareDevelopmentReactFrontendWebDeveloper.png",
      issuer: "Ministry of Communications and Information Technology",
      category: "technical",
      date: "May 2025",
      duration: "November to May 2025",
      score: "Excellent",
      description:
        "Advanced frontend development program using React, including practical projects and intensive training under ministry supervision.",
      skills: [
        "React",
        "JavaScript",
        "HTML5",
        "CSS3",
        "Git",
        "Responsive Design",
        "API Integration",
      ],
      details: {
        program: "Digital Egypt Pioneers Program",
        specialization: "Software Development - React Frontend Web Developer",
        organization: "Ministry of Communications and Information Technology",
        period: "November 2024 to May 2025",
        issuedBy: "Dr. Hesham Farouk - Technology Development Consultant, MCIT",
        validation:
          "Officially certified by the Ministry of Communications and IT",
      },
    },
    {
      id: 2,
      title: "Business English Track - Round 2",
      image: "completedBusinessEnglishTrack.jpg",
      issuer: "Ministry of Communications and Information Technology",
      category: "soft",
      date: "May 2025",
      duration: "7 months",
      score: "Excellent",
      description:
        "Intensive business English course under Digital Egypt Pioneers Initiative, focusing on professional communication and presentation skills.",
      skills: [
        "Business English",
        "Professional Communication",
        "Presentation Skills",
        "Email Writing",
        "Negotiation",
      ],
      details: {
        program: "Business English Track - Round 2",
        organization:
          "Ministry of Communications and IT - SYE English Community",
        period: "November 2024 to May 2025",
        level: "Advanced",
        focus: "Business English and Professional Skills",
      },
    },
    {
      id: 3,
      title: "UX/UI Design Course",
      image: "uix.jpg",
      issuer: "Information Technology Institute",
      category: "design",
      date: "August 2025",
      duration: "60 hours",
      score: "Excellent",
      description:
        "Comprehensive course in user interface and user experience design fundamentals, covering research, planning, prototyping, and testing.",
      skills: [
        "UX Research",
        "UI Design",
        "Wireframing",
        "Prototyping",
        "Figma",
        "Adobe XD",
        "User Testing",
      ],
      details: {
        topics: [
          "UX Fundamentals & Design Research",
          "Design Process, Emphasis, Define and Ideate",
          "Concept to Low-Fidelity Prototyping",
          "High-Fidelity Prototyping to Post-Launch Analysis",
        ],
        totalHours: 60,
        institute: "Information Technology Institute (ITI)",
        issuedBy: "Dr. Heba Saleh - Chairman, Information Technology Institute",
      },
    },
    {
      id: 4,
      title: "Front End Development Using React",
      image: "reactjs.jpg",
      issuer: "Information Technology Institute",
      category: "development",
      date: "September 2024",
      duration: "150 hours",
      score: "Excellent",
      description:
        "Advanced frontend development course using React and modern web technologies, with comprehensive practical projects.",
      skills: [
        "React.js",
        "JavaScript ES6+",
        "HTML5",
        "CSS3",
        "Bootstrap",
        "REST APIs",
        "State Management",
      ],
      details: {
        topics: ["JavaScript", "ECMA Script", "HTML5", "Bootstrap", "ReactJS"],
        totalHours: 150,
        period: "July 15 to September 15, 2024",
        institute: "Information Technology Institute",
      },
    },
    {
      id: 5,
      title: "Development Using .NET",
      image: "dotnet.jpg",
      issuer: "Information Technology Institute",
      category: "development",
      date: "February 2023",
      duration: "60 hours",
      score: "Excellent",
      description:
        "Course in application development using .NET and SQL Server, covering programming fundamentals and database design.",
      skills: [
        ".NET",
        "C#",
        "SQL Server",
        "ASP.NET",
        "Entity Framework",
        "Database Design",
      ],
      details: {
        topics: [
          "C# Programming",
          "SQL Server",
          "ASP.NET MVC",
          "Entity Framework",
        ],
        totalHours: 60,
        period: "January 29 to February 9, 2023",
      },
    },
    {
      id: 6,
      title: "SEO for Beginners Course",
      image: "SEO.png",
      issuer: "Salla Academy",
      category: "business",
      date: "December 2025",
      duration: "1 hour",
      score: "Excellent",
      description:
        "Basic course in Search Engine Optimization (SEO) for beginners, covering SEO fundamentals and website optimization practices.",
      skills: [
        "SEO Basics",
        "Keyword Research",
        "On-Page SEO",
        "Technical SEO",
        "Content Optimization",
      ],
      details: {
        instructor: "Rakan Al-Juhani",
        hours: 1,
        issuedDate: "December 4, 2025",
        platform: "Salla Academy",
      },
    },
    {
      id: 7,
      title: "CIB Summer Program - The Green Leap",
      image: "CIB.jpg",
      issuer: "Commercial International Bank (CIB)",
      category: "business",
      date: "July 2025",
      duration: "1 month",
      score: "Excellent",
      description:
        "Summer training program focusing on sustainability and green finance, including workshops and sessions with banking experts.",
      skills: [
        "Sustainable Finance",
        "ESG Principles",
        "Banking Operations",
        "Green Investments",
        "Corporate Sustainability",
      ],
      details: {
        program: "CIB Summer Program - The Green Leap",
        partners: ["Frankfurt School", "PROPARCO", "EUROMONEY", "X University"],
        focus: "Green Finance and Sustainability in Banking",
      },
    },
    {
      id: 8,
      title: "ALX Augmented Professional Development Skills Program",
      image: "AiCareerEssentials.png",
      issuer: "ALX",
      category: "soft",
      date: "August 2024",
      duration: "8 weeks",
      score: "Excellent",
      description:
        "Professional skills development program in the digital age using AI, focusing on leadership and innovation.",
      skills: [
        "AI Tools",
        "Professional Development",
        "Leadership",
        "Digital Communication",
        "Innovation",
      ],
      details: {
        program: "Augmented Professional Development Skills in the Digital Age",
        duration: "8 weeks",
        issuedBy: "ALX Group",
        validation: "ALX certified with verification code",
      },
    },
    {
      id: 9,
      title: "Front-end Web Development Diploma",
      image: "SEF.jpeg",
      issuer: "Software Engineering Future (SEF)",
      category: "development",
      date: "July 2024",
      duration: "4 months",
      score: "95.5%",
      description:
        "Specialized diploma in frontend web development, with comprehensive practical evaluation and real projects.",
      skills: [
        "Frontend Development",
        "Web Standards",
        "Performance Optimization",
        "Cross-Browser Compatibility",
        "Web Accessibility",
      ],
      details: {
        studentId: "274122331",
        duration: "4 months",
        score: "95.5%",
        issuedDate: "July 29, 2024",
      },
    },
    {
      id: 10,
      title: "Empower Your Future Training Course",
      image: "EmpowerYourFuture.png",
      issuer: "Raya Customer Experience",
      category: "soft",
      date: "Not specified",
      duration: "25 hours",
      score: "Excellent",
      description:
        "Training course to empower the future under Misr El Kheir Foundation supervision, focusing on personal and professional development.",
      skills: [
        "Personal Development",
        "Career Planning",
        "Communication Skills",
        "Problem Solving",
        "Teamwork",
      ],
      details: {
        hours: 25,
        funder: "Raya Customer Experience",
        implementer: "Rowad Initiative",
        supervisor: "Misr El Kheir Foundation",
      },
    },
    {
      id: 11,
      title: "Professional Diploma in Social Media Marketing & Management",
      image: "SocialMediaMarketingAndManagement.jpg",
      issuer: "Udemy - MTF Institute",
      category: "business",
      date: "January 2024",
      duration: "2 hours",
      score: "Excellent",
      description:
        "Professional diploma in social media marketing and management, including digital marketing strategies and content management.",
      skills: [
        "Social Media Marketing",
        "Content Strategy",
        "Digital Advertising",
        "Analytics",
        "Brand Management",
      ],
      details: {
        certificateId: "UC-d33210be-6bcf-4cdd-b1c4-a07c3560a32a",
        issuedDate: "January 18, 2024",
        duration: "2 hours",
        platform: "Udemy",
      },
    },
    {
      id: 12,
      title: "WordPress Crash Course: Build any Website in Minutes!",
      image: "wordpress.jpg",
      issuer: "Udemy - Meta Brains",
      category: "development",
      date: "October 2025",
      duration: "2.5 hours",
      score: "Excellent",
      description:
        "Rapid course to learn building websites using WordPress, including content management and advanced customization.",
      skills: [
        "WordPress",
        "CMS",
        "Theme Development",
        "Plugin Management",
        "Website Deployment",
      ],
      details: {
        certificateId: "UC-1b5f9aa7-7b81-47c7-8df8-ba59e4e83ac6",
        issuedDate: "October 13, 2025",
        duration: "2.5 hours",
        platform: "Udemy",
      },
    },
  ],
  labels: {
    allCertificates: "All Certificates",
    showingXofY: "Showing {count} of {total} certificates",
    certificateNumber: "Certificate #{number}",
    viewFullDetails: "View Full Details",
    downloadCertificate: "Download Certificate",
    verifyCertificate: "Verify Certificate",
    close: "Close",

    // Categories
    technical: "Technical",
    soft: "Soft Skills",
    design: "Design",
    business: "Business & Marketing",
    development: "Development",

    // Component labels
    acquiredSkills: "Acquired Skills",
    programDetails: "Program Details",
    certificateDescription: "Certificate Description",
    duration: "Duration",
    skills: "Skills",

    // Certificate details keys
    program: "Program",
    specialization: "Specialization",
    organization: "Organization",
    period: "Period",
    issuedBy: "Issued By",
    validation: "Validation",
    level: "Level",
    focus: "Focus",
    topics: "Topics",
    totalHours: "Total Hours",
    institute: "Institute",
    instructor: "Instructor",
    issuedDate: "Issued Date",
    platform: "Platform",
    partners: "Partners",
    studentId: "Student ID",
    score: "Score",
    funder: "Funder",
    implementer: "Implementer",
    supervisor: "Supervisor",
    certificateId: "Certificate ID",
  },
};
