"use client";

export const webSolutionsContent = {
  title: "حلول الويب والتجارة الإلكترونية",
  description: "تحويل الأفكار إلى تجارب رقمية استثنائية تؤدي إلى نتائج ملموسة",
  heroTitle: "بناء مستقبل رقمي ناجح",
  heroDescription:
    "أطور حلول ويب وتجارة إلكترونية متكاملة تركز على الأداء والتحويل وتحقيق الأهداف التجارية",

  projects: [
    {
      id: 1,
      title: "لوحة تحكم متجر Pearline",
      category: "لوحة التحكم",
      duration: "2:45",
      youtubeId: "CCav701xyCY",
      description:
        "تطوير واجهة إدارة متجر Pearline باستخدام React و Tailwind CSS مع نظام تحليلات متقدم",
      technologies: ["React", "Tailwind CSS", "Chart.js", "React Query"],
      features: [
        "لوحة تحكم تفاعلية",
        "مخططات وإحصائيات حية",
        "إدارة الطلبات والمنتجات",
        "نظام تنبيهات ذكي",
      ],
      challenge: "حاجة العميل لنظام مراقبة وإدارة متكامل لمتجره الإلكتروني",
      solution: "تطوير لوحة تحكم مخصصة تعرض جميع البيانات المهمة في مكان واحد",
      results: "تحسين كفاءة الإدارة بنسبة 40%، تقليل وقت المعالجة بنسبة 60%",
      liveUrl: "#",
    },
    {
      id: 2,
      title: "موقع Kleitech للكشف المبكر عن الفشل الكلوي",
      category: "منصة طبية",
      duration: "3:15",
      youtubeId: "CCav701xyCY",
      description:
        "منصة طبية متخصصة في الكشف المبكر عن الفشل الكلوي عبر الذكاء الاصطناعي",
      technologies: ["Next.js", "TypeScript", "TensorFlow.js", "MongoDB"],
      features: [
        "تحليل بيانات المريض",
        "تقارير طبية تفاعلية",
        "نظام تنبيهات طبية",
        "واجهة متعددة اللغات",
      ],
      challenge: "توفير نظام تشخيص طبي دقيق وسهل الاستخدام للأطباء والمرضى",
      solution: "بناء منصة متكاملة مع خوارزميات ذكاء اصطناعي للتحليل",
      results: "زيادة دقة التشخيص بنسبة 35%، تحسين تجربة المستخدم للمرضى",
      liveUrl: "#",
    },
    {
      id: 3,
      title: "لوحة تحكم منصة النقل OTM",
      category: "النقل",
      duration: "2:30",
      youtubeId: "CCav701xyCY",
      description: "نظام إدارة شحنات ومنصة نقل متكاملة مع تتبع حي للشحنات",
      technologies: ["React", "Node.js", "Socket.io", "Google Maps API"],
      features: [
        "تتبع الشحنات الحي",
        "إدارة السائقين",
        "نظام الفواتير",
        "تقارير الأداء",
      ],
      challenge: "تتبع الشحنات في الوقت الفعلي وإدارة العمليات اللوجستية",
      solution: "تطوير نظام تتبع متكامل مع خرائط مباشرة وإشعارات فورية",
      results: "تقليل وقت التتبع بنسبة 70%، زيادة رضا العملاء بنسبة 45%",
      liveUrl: "#",
    },
    {
      id: 4,
      title: "نظام إدارة التعلم (LMS)",
      category: "التعليم",
      duration: "3:45",
      youtubeId: "CCav701xyCY",
      description: "منصة تعلم إلكتروني متكاملة مع فصول افتراضية وتقييمات ذكية",
      technologies: ["Next.js", "MongoDB", "WebRTC", "Stripe"],
      features: [
        "فصول افتراضية",
        "تقييمات تلقائية",
        "شهادات معتمدة",
        "نظام متابعة الطلاب",
      ],
      challenge: "إنشاء بيئة تعليمية تفاعلية عبر الإنترنت",
      solution: "منصة متكاملة مع فصول مباشرة ونظام تقييم ذكي",
      results: "زيادة مشاركة الطلاب بنسبة 60%، تحسين نتائج التعلم",
      liveUrl: "#",
    },
    {
      id: 5,
      title: "متجر Pearline الإلكتروني",
      category: "التجارة الإلكترونية",
      duration: "2:15",
      youtubeId: "CCav701xyCY",
      description: "متجر إلكتروني متكامل لمنتجات التجميل والعناية الشخصية",
      technologies: ["WordPress", "WooCommerce", "Elementor", "Arabic Support"],
      features: [
        "تصميم عربي متجاوب",
        "بوابة دفع متعددة",
        "نظام كوبونات",
        "تتبع الطلبات",
      ],
      challenge: "إنشاء متجر إلكتروني سهل الاستخدام مع دعم اللغة العربية",
      solution: "تطوير متجر مخصص مع واجهة مستخدم بسيطة وتجربة شراء سلسة",
      results: "زيادة المبيعات بنسبة 150%، تحسين معدل التحويل بنسبة 30%",
      liveUrl: "#",
    },
    {
      id: 6,
      title: "متجر WordPress Porto",
      category: "التجارة الإلكترونية",
      duration: "2:00",
      youtubeId: "CCav701xyCY",
      description:
        "تصميم وتطوير متجر إلكتروني باستخدام WordPress مع تصاميم فريدة",
      technologies: ["WordPress", "Porto Theme", "WooCommerce", "Custom CSS"],
      features: [
        "تصميم فريد",
        "تحسين SEO",
        "سرعة تحميل عالية",
        "دعم متعدد اللغات",
      ],
      challenge: "تحسين سرعة وأداء متجر WordPress مع الحفاظ على التصميم الفريد",
      solution: "تحسين شفرة الموقع وإضافة تقنيات التخزين المؤقت",
      results: "تحسين سرعة التحميل بنسبة 65%، زيادة ظهور محرك البحث",
      liveUrl: "#",
    },
  ],

  skills: [
    { name: "React", iconName: "FaReact" },
    { name: "Next.js", iconName: "SiNextdotjs" },
    { name: "TypeScript", iconName: "SiTypescript" },
    { name: "Tailwind CSS", iconName: "SiTailwindcss" },
    { name: "WordPress", iconName: "FaWordpress" },
    { name: "Shopify", iconName: "FaShopify" },
    { name: "Node.js", iconName: "SiNodedotjs" },
    { name: "Express.js", iconName: "SiExpress" },
    { name: "MongoDB", iconName: "SiMongodb" },
    { name: "Performance", iconName: "FaBolt" },
    { name: "Security", iconName: "FaShieldAlt" },
    { name: "SEO", iconName: "FaSearch" },
    { name: "UX/UI Design", iconName: "FaPalette" },
    { name: "Responsive", iconName: "FaMobileAlt" },
    { name: "Analytics", iconName: "FaChartLine" },
  ],

  optimizationServices: [
    {
      id: 1,
      category: "السلامة والأمان",
      icon: "FaShieldAlt",
      color: "from-red-500 to-red-700",
      items: [
        "شهادات SSL وتشفير البيانات",
        "جدران الحماية (Firewall)",
        "نسخ احتياطي تلقائي على Google Drive + Hostinger",
        "حماية من الهجمات الإلكترونية",
        "مراقبة مستمرة للثغرات الأمنية",
      ],
    },
    {
      id: 2,
      category: "تحسين السرعة والأداء",
      icon: "FaBolt",
      color: "from-yellow-500 to-orange-500",
      items: [
        "تحسين سرعة التحميل Core Web Vitals",
        "نتائج Google PageSpeed (جوال وسطح المكتب)",
        "تحسين الاستجابة على الجوال Mobile responsiveness",
        "ضبط التخزين المؤقت للجوال",
        "تحسين وقت التجاوب الأولي (FCP, LCP)",
      ],
    },
    {
      id: 3,
      category: "الصيانة التقنية",
      icon: "FaCog",
      color: "from-blue-500 to-cyan-500",
      items: [
        "تنظيف بنية الروابط والـ Database",
        "إصلاح الأخطاء وفحص الروابط المعطلة",
        "إصلاح 404 خاصة في بوابات الدفع",
        "التوافق مع جميع المتصفحات Cross-browser compatibility",
        "تنظيف الملفات والبيانات غير المستخدمة",
      ],
    },
    {
      id: 4,
      category: "الاستضافة والمحتوى",
      icon: "FaServer",
      color: "from-green-500 to-emerald-500",
      items: [
        "استضافة محسنة + شبكة CDN",
        "تحديثات CMS والقوالب والإضافات",
        "تحديثات الاشتراكات والدفع",
        "خرائط الموقع XML التحديث التلقائي",
        "إدارة ومتابعة استضافة الموقع",
      ],
    },
    {
      id: 5,
      category: "تحسين الوسائط",
      icon: "FaImage",
      color: "from-purple-500 to-pink-500",
      items: [
        "صور عالية الجودة دون التأثير على السرعة",
        "تحميل الصور السريع Lazy Loading",
        "تحسين حجم وتنسيق الصور",
        "مكتبة الوسائط المنظمة",
        "تحويل الصور إلى WebP للتحميل الأسرع",
      ],
    },
    {
      id: 6,
      category: "الدعم متعدد اللغات",
      icon: "FaGlobe",
      color: "from-indigo-500 to-blue-700",
      items: [
        "إصلاح مشاكل الثنائية اللغوية",
        "ترجمة متكاملة",
        "تحسين SEO لكل لغة",
        "واجهة مستخدم متعددة اللغات",
        "دعم RTL للغة العربية",
      ],
    },
  ],

  ctaTitle: "مستعد لتحويل فكرتك إلى واقع رقمي؟",
  ctaDescription:
    "دعونا نناقش مشروعك ونبني معًا حلًا رقميًا يلبي توقعاتك ويتجاوزها",
  ctaButton1: "ابدأ مشروعك الآن",
  ctaButton2: "طلب استشارة مجانية",

  viewProject: "مشاهدة المشروع",
  watchDemo: "عرض توضيحي",
  mainFeatures: "المميزات الرئيسية:",
  technologiesUsed: "التقنيات المستخدمة:",
  viewLiveSite: "عرض الموقع اونلاين",

  optimizationTitle: "خدمات تحسين وصيانة المواقع",
  closeModal: "إغلاق",
};
